sonar.projectKey=Java_practise
sonar.projectName=Java_practise
sonar.projectVersion=1.0

sonar.sources=.
sonar.java.binaries=bin
sonar.sourceEncoding=UTF-8

sonar.host.url=http://localhost:9000
sonar.token=sqp_3b8860f4bb839be74a55e1e283ed9e9b0a3af48d